### PR TITLE
Load smaller bg image on smaller screens

### PR DESCRIPTION
**Pull request by deweydell**
- Create small and large versions of page-intro background image (original size: 157KB, now large size: 131KB and small size: 76KB)
- Run both page-intro and faq section bg images through imageOptim
- Use media queries to load smaller image at <1400px
- Add backup background color to page-intro and faq section background properties so the sections will have a bg color if images fail to load.

### CODE REVIEW

**Comment by deweydell** [comment]
Also, up for debate, but I changed the page-intro background image's x and y positions to display from the bottom and left of the image (rather than center and center). I feel that left side of the photo has more relevant information than the center on a mobile screen and that the foreground of the photo should fill more of the frame.
screen shot 2017-07-01 at 3 56 19 pm

**Review by jarmstrng — APPROVED** [review]
heck yeah, great ideas, 💯 approve changing to bottom left. your employer is lucky to have you 👍 :shipit:

**Comment by jarmstrng** [comment]
I got all excited and forgot to deploy this to staging to check it on my phone 🙄

**Comment by jarmstrng** [comment]
There was a slightly weird shift of the intro image after about a second, go ahead and merge and deploy this now but let me know if you get the same thing on your phone and maybe we can look into it later

**Pull request merged**
